# This file was generated by GoReleaser. DO NOT EDIT.
class Bump < Formula
  desc "Command-line to bump version in a git repository."
  homepage "https://github.com/guilhem/bump"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/guilhem/bump/releases/download/v0.0.4/bump_0.0.4_Darwin_x86_64.tar.gz"
    sha256 "863eab50c3aefe355e2839779c674f0de83ff39540e21badfbcef7a791ab01f5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/guilhem/bump/releases/download/v0.0.4/bump_0.0.4_Linux_x86_64.tar.gz"
      sha256 "bd330a5d9ba112d77151df7c73a362f78bb1897b4d3fac84dc3242302b51e7a7"
    end
  end

  def install
    bin.install "bump"
  end
end
